language: bash
sudo: required

# establish environment variables
env:
  global:
    - GH_USER_NAME="oleggorj"
    - GH_REPO="OlegGorj/tf-modules-aws-bastion"

before_install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.11.3/terraform_0.11.3_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - sudo apt-get install git-all
