region      = "ca-central-1"
key_path    = "~/.ssh/"
key_name	= "dev_key"
encrypt = "true"
state_bucket = "ca-central-1.aws-terraform-state-bucket"
bucket_key = "terraform/dev/tf.tfstate"
env = "dev"
