region      = "ca-central-1"
key_path    = "~/.ssh/"
key_name	= "dev_key"
encrypt = "true"
state_bucket = "ca-central-1.aws-terraform-state-bucket"
bucket_key = "terraform/dev/bastionbox.tfstate"
env = "dev"

ec2_bastion_instance_type    = "t2.micro"
ec2_bastion_storage_type     = "gp2"
ec2_bastion_user            = "ubuntu"

account_id = "317565499837"
ip_allow2 = ""
ip_allow1 = ""
ip_allow3 = ""
ip_allow4 = ""
ip_allow5 = ""
